name: "Tests"

on:
  pull_request:
    branches:
      - master
      - 'release-'
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

env:
  RETESTITEMS_NWORKERS: 4
  RETESTITEMS_NWORKER_THREADS: 2

jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        group:
          - "MIRK"
          - "MISC"
          - "SHOOTING"
          - "FIRK(EXPANDED)"
          - "FIRK(NESTED)"
          - "WRAPPERS"
        julia-version: ['1.10']
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      group: "${{ matrix.group }}"
    secrets: "inherit"
